const ActionTypes = {
  LOAD_DATA: "LOAD_DATA",
  ADD_NODE: "ADD_NODE",
  DELETE_NODE: "DELETE_NODE",
  MOVE_NODE_BACK: "MOVE_NODE_BACK",
  MOVE_NODE_FORWARD: "MOVE_NODE_FORWARD",
  UPDATE_NODE_TITLE: "UPDATE_NODE_TITLE",
};

export default ActionTypes;